-- Insert sample data into the people table
-- This script adds comprehensive sample data for the people page

-- First, let's clear any existing data (optional)
-- DELETE FROM people;

-- Insert sample people data
INSERT INTO people (
  name, title, specialization, description, detailed_description,
  experience, category, status, verified, featured, availability,
  email, phone, location, website, linkedin,
  rating, review_count, projects, completion_rate, response_time,
  hourly_rate, monthly_rate, project_rate,
  icon_name, color_gradient, accent_color,
  expertise, languages, education, certifications, skills, testimonials, recent_projects, achievements
) VALUES 
(
  'CS Anchal Chopra',
  'Company Secretary & Legal Expert',
  'Corporate Law & Compliance',
  'Expert in corporate governance and legal compliance with extensive experience in POSH implementation and workplace safety regulations.',
  'With over a decade of experience in corporate law and compliance, CS Anchal Chopra has established herself as a leading authority in POSH implementation and workplace safety. Her comprehensive approach combines legal expertise with practical implementation strategies, helping organizations create safer, more inclusive work environments.',
  '10+ years',
  'legal',
  'premium',
  true,
  true,
  'Available',
  'anchal.chopra@ureposh.com',
  '+91 98765 43210',
  'New Delhi, India',
  'www.anchalchopra.com',
  'linkedin.com/in/anchalchopra',
  4.9,
  187,
  156,
  98,
  '2 hours',
  '₹5,000',
  '₹1,50,000',
  '₹25,000',
  'Scale',
  'from-pink-500 to-rose-600',
  'pink',
  '["Corporate Governance", "Legal Compliance", "POSH Implementation", "Risk Management", "Company Law", "Regulatory Advisory"]',
  '["English", "Hindi", "Punjabi"]',
  '[{"degree": "Company Secretary", "institution": "Institute of Company Secretaries of India", "year": "2012"}, {"degree": "LLB", "institution": "Delhi University", "year": "2010"}]',
  '["Certified POSH Trainer", "Corporate Governance Expert", "Risk Management Professional"]',
  '[{"name": "Corporate Law", "level": 95}, {"name": "POSH Compliance", "level": 98}, {"name": "Risk Management", "level": 90}, {"name": "Training & Development", "level": 92}]',
  '[{"id": 1, "client": "TechCorp Solutions", "feedback": "Exceptional expertise in POSH implementation. Made the entire process seamless.", "rating": 5, "date": "2024-01-15", "projectType": "POSH Implementation"}, {"id": 2, "client": "Global Manufacturing", "feedback": "Professional approach and deep knowledge of corporate compliance.", "rating": 5, "date": "2023-12-20", "projectType": "Compliance Audit"}, {"id": 3, "client": "StartupHub India", "feedback": "Outstanding legal guidance and support throughout our compliance journey.", "rating": 5, "date": "2023-11-10", "projectType": "Legal Advisory"}]',
  '[{"title": "POSH Policy Implementation", "client": "Tech Solutions Ltd", "duration": "3 months", "status": "Completed"}, {"title": "Corporate Governance Review", "client": "Manufacturing Corp", "duration": "2 months", "status": "In Progress"}]',
  '["Top 10 Corporate Lawyers in Delhi - 2023", "Excellence in POSH Implementation Award", "Best Legal Advisor - Startup Category"]'
),
(
  'CA Shweta Gupta',
  'Chartered Accountant & Financial Advisor',
  'Financial Compliance & Risk Management',
  'Specialized in financial compliance and risk assessment for workplace safety programs with expertise in audit management and strategic financial planning.',
  'CA Shweta Gupta brings comprehensive financial expertise to workplace safety and compliance programs. Her analytical approach to risk assessment and financial planning ensures organizations can implement effective POSH programs while maintaining fiscal responsibility.',
  '8+ years',
  'finance',
  'standard',
  true,
  false,
  'Available',
  'shweta.gupta@ureposh.com',
  '+91 98765 43211',
  'Mumbai, India',
  'www.shwetaguptaca.com',
  'linkedin.com/in/shwetaguptaca',
  4.8,
  134,
  112,
  96,
  '3 hours',
  '₹4,500',
  '₹1,20,000',
  '₹20,000',
  'Calculator',
  'from-rose-500 to-pink-600',
  'rose',
  '["Financial Compliance", "Risk Assessment", "Audit Management", "Strategic Planning", "Tax Advisory", "Financial Reporting"]',
  '["English", "Hindi", "Marathi"]',
  '[{"degree": "Chartered Accountant", "institution": "Institute of Chartered Accountants of India", "year": "2015"}, {"degree": "B.Com", "institution": "Mumbai University", "year": "2013"}]',
  '["Certified Risk Management Professional", "Financial Planning Expert", "Audit Specialist"]',
  '[{"name": "Financial Analysis", "level": 94}, {"name": "Risk Assessment", "level": 91}, {"name": "Audit Management", "level": 88}, {"name": "Compliance Reporting", "level": 93}]',
  '[{"id": 1, "client": "Financial Services Corp", "feedback": "Outstanding financial compliance expertise. Helped optimize our budget significantly.", "rating": 5, "date": "2024-01-10", "projectType": "Financial Audit"}, {"id": 2, "client": "Investment Group", "feedback": "Excellent risk assessment and strategic financial planning.", "rating": 5, "date": "2023-12-15", "projectType": "Risk Management"}]',
  '[{"title": "Financial Compliance Audit", "client": "Banking Solutions", "duration": "4 months", "status": "Completed"}, {"title": "Risk Assessment Framework", "client": "Insurance Corp", "duration": "2 months", "status": "In Progress"}]',
  '["Best CA in Financial Compliance - 2023", "Excellence in Risk Management Award", "Top Financial Advisor - Mumbai"]'
),
(
  'Adv. Shringarika Tyagi',
  'Legal Academic & Gender Justice Expert',
  'POSH Law & Policy Research',
  'UGC-NET qualified legal academic pursuing Ph.D. in Law, specializing in gender justice and POSH compliance with extensive research background.',
  'Adv. Shringarika Tyagi combines academic excellence with practical legal expertise in gender justice and POSH law. Her research-driven approach to policy development and implementation has helped shape modern workplace safety standards across various industries.',
  '12+ years',
  'legal',
  'premium',
  true,
  true,
  'Available',
  'shringarika.tyagi@ureposh.com',
  '+91 98765 43212',
  'Delhi, India',
  'www.shringarikatyagi.com',
  'linkedin.com/in/shringarikatyagi',
  4.9,
  203,
  178,
  99,
  '1 hour',
  '₹6,000',
  '₹1,80,000',
  '₹30,000',
  'GraduationCap',
  'from-fuchsia-500 to-purple-600',
  'fuchsia',
  '["POSH Law", "Gender Justice", "Policy Research", "Legal Education", "Academic Research", "Constitutional Law"]',
  '["English", "Hindi", "Sanskrit"]',
  '[{"degree": "Ph.D. in Law (Pursuing)", "institution": "Jawaharlal Nehru University", "year": "2024"}, {"degree": "LLM", "institution": "Delhi University", "year": "2012"}, {"degree": "LLB", "institution": "Delhi University", "year": "2010"}]',
  '["UGC-NET Qualified", "Gender Justice Expert", "POSH Law Specialist", "Constitutional Law Expert"]',
  '[{"name": "POSH Law", "level": 98}, {"name": "Gender Justice", "level": 96}, {"name": "Policy Research", "level": 94}, {"name": "Legal Training", "level": 95}]',
  '[{"id": 1, "client": "Government Think Tank", "feedback": "Exceptional research capabilities and deep understanding of gender justice issues.", "rating": 5, "date": "2024-01-20", "projectType": "Policy Research"}, {"id": 2, "client": "Legal Education Institute", "feedback": "Outstanding academic expertise and practical implementation knowledge.", "rating": 5, "date": "2023-12-25", "projectType": "Legal Training"}]',
  '[{"title": "POSH Policy Framework Development", "client": "Government Agency", "duration": "6 months", "status": "Completed"}, {"title": "Gender Justice Research Study", "client": "Academic Institution", "duration": "8 months", "status": "In Progress"}]',
  '["Best Research Paper on Gender Justice - 2023", "Excellence in Legal Education Award", "Top POSH Law Expert - India"]'
),
(
  'CA Sarvagya Goyal',
  'Chartered Accountant & Audit Specialist',
  'Compliance Auditing & Process Optimization',
  'Expert in compliance auditing and financial oversight for organizational safety programs with focus on process optimization and quality assurance.',
  'CA Sarvagya Goyal specializes in creating robust audit frameworks for workplace safety programs. His systematic approach to compliance auditing ensures organizations maintain the highest standards while optimizing operational efficiency.',
  '7+ years',
  'finance',
  'standard',
  true,
  false,
  'Available',
  'sarvagya.goyal@ureposh.com',
  '+91 98765 43213',
  'Bangalore, India',
  'www.sarvagyagoyal.com',
  'linkedin.com/in/sarvagyagoyal',
  4.7,
  98,
  89,
  94,
  '4 hours',
  '₹4,000',
  '₹1,00,000',
  '₹18,000',
  'Calculator',
  'from-pink-400 to-rose-500',
  'pink',
  '["Compliance Auditing", "Financial Oversight", "Process Optimization", "Quality Assurance", "Internal Controls", "Risk Assessment"]',
  '["English", "Hindi", "Kannada"]',
  '[{"degree": "Chartered Accountant", "institution": "Institute of Chartered Accountants of India", "year": "2016"}, {"degree": "B.Com", "institution": "Bangalore University", "year": "2014"}]',
  '["Certified Internal Auditor", "Process Optimization Expert", "Quality Assurance Specialist"]',
  '[{"name": "Audit Management", "level": 92}, {"name": "Compliance Review", "level": 89}, {"name": "Process Optimization", "level": 87}, {"name": "Quality Assurance", "level": 85}]',
  '[{"id": 1, "client": "Manufacturing Group", "feedback": "Excellent audit capabilities and attention to detail in compliance matters.", "rating": 5, "date": "2024-01-05", "projectType": "Compliance Audit"}]',
  '[{"title": "Internal Audit Framework", "client": "Tech Company", "duration": "3 months", "status": "Completed"}]',
  '["Best Auditor - Bangalore Chapter", "Excellence in Process Optimization"]'
),
(
  'Adv. Pradeep Kumar',
  'Legal Advisor & Litigation Expert',
  'Employment Law & Dispute Resolution',
  'Experienced in employment law and workplace dispute resolution with focus on harassment cases and legal counseling.',
  'Adv. Pradeep Kumar brings extensive litigation experience to workplace dispute resolution. His expertise in employment law and mediation has helped numerous organizations resolve complex harassment cases while maintaining workplace harmony.',
  '15+ years',
  'legal',
  'premium',
  true,
  false,
  'Busy',
  'pradeep.kumar@ureposh.com',
  '+91 98765 43214',
  'Chennai, India',
  'www.pradeepkumarlaw.com',
  'linkedin.com/in/pradeepkumarlaw',
  4.8,
  245,
  198,
  97,
  '6 hours',
  '₹7,000',
  '₹2,00,000',
  '₹35,000',
  'Scale',
  'from-rose-400 to-pink-500',
  'rose',
  '["Employment Law", "Dispute Resolution", "Litigation", "Legal Counseling", "Contract Law", "Labor Relations"]',
  '["English", "Hindi", "Tamil"]',
  '[{"degree": "LLM", "institution": "Madras University", "year": "2010"}, {"degree": "LLB", "institution": "Madras University", "year": "2008"}]',
  '["Employment Law Expert", "Certified Mediator", "Litigation Specialist"]',
  '[{"name": "Employment Law", "level": 96}, {"name": "Dispute Resolution", "level": 94}, {"name": "Litigation", "level": 93}, {"name": "Legal Counseling", "level": 91}]',
  '[{"id": 1, "client": "Corporate Legal Dept", "feedback": "Outstanding litigation skills and deep knowledge of employment law.", "rating": 5, "date": "2024-01-12", "projectType": "Employment Dispute"}]',
  '[{"title": "Employment Dispute Resolution", "client": "Large Corporation", "duration": "4 months", "status": "Completed"}]',
  '["Top Employment Lawyer - Chennai", "Excellence in Dispute Resolution"]'
),
(
  'Dr. Meera Sharma',
  'Organizational Psychologist & HR Consultant',
  'Workplace Psychology & Behavioral Training',
  'Specialized in workplace psychology, behavioral training, and creating psychologically safe work environments with expertise in trauma-informed approaches.',
  'Dr. Meera Sharma combines clinical psychology expertise with organizational development to create psychologically safe workplaces. Her trauma-informed approach to workplace training has transformed organizational cultures across various industries.',
  '9+ years',
  'psychology',
  'standard',
  true,
  false,
  'Available',
  'meera.sharma@ureposh.com',
  '+91 98765 43215',
  'Pune, India',
  'www.meerasharma.com',
  'linkedin.com/in/meerasharma',
  4.9,
  156,
  134,
  97,
  '3 hours',
  '₹5,500',
  '₹1,40,000',
  '₹28,000',
  'Brain',
  'from-pink-300 to-rose-400',
  'pink',
  '["Workplace Psychology", "Behavioral Training", "Trauma-Informed Care", "Employee Wellness", "Conflict Resolution", "Leadership Development"]',
  '["English", "Hindi", "Marathi"]',
  '[{"degree": "Ph.D. in Psychology", "institution": "Pune University", "year": "2015"}, {"degree": "M.A. Psychology", "institution": "Pune University", "year": "2012"}]',
  '["Licensed Clinical Psychologist", "Trauma-Informed Care Specialist", "Organizational Development Expert"]',
  '[{"name": "Workplace Psychology", "level": 96}, {"name": "Behavioral Training", "level": 94}, {"name": "Trauma-Informed Care", "level": 92}, {"name": "Employee Wellness", "level": 90}]',
  '[{"id": 1, "client": "Tech Startup", "feedback": "Exceptional understanding of workplace psychology and employee wellness.", "rating": 5, "date": "2024-01-08", "projectType": "Workplace Psychology"}]',
  '[{"title": "Employee Wellness Program", "client": "Software Company", "duration": "5 months", "status": "In Progress"}]',
  '["Best Organizational Psychologist - Pune", "Excellence in Employee Wellness"]'
),
(
  'Adv. Priya Singh',
  'Corporate Lawyer & Compliance Specialist',
  'Corporate Governance & Regulatory Compliance',
  'Expert in corporate governance, regulatory compliance, and board advisory services with focus on creating robust compliance frameworks.',
  'Adv. Priya Singh is a seasoned corporate lawyer with extensive experience in corporate governance and regulatory compliance. She has helped numerous organizations establish effective compliance frameworks and navigate complex regulatory landscapes.',
  '11+ years',
  'legal',
  'premium',
  true,
  true,
  'Available',
  'priya.singh@ureposh.com',
  '+91 98765 43216',
  'Gurgaon, India',
  'www.priyasinghlaw.com',
  'linkedin.com/in/priyasinghlaw',
  4.8,
  167,
  145,
  96,
  '4 hours',
  '₹6,500',
  '₹1,75,000',
  '₹32,000',
  'Scale',
  'from-indigo-500 to-purple-600',
  'indigo',
  '["Corporate Governance", "Regulatory Compliance", "Board Advisory", "Risk Management", "Corporate Law", "Mergers & Acquisitions"]',
  '["English", "Hindi", "Punjabi"]',
  '[{"degree": "LLM Corporate Law", "institution": "National Law School", "year": "2013"}, {"degree": "LLB", "institution": "Delhi University", "year": "2011"}]',
  '["Corporate Governance Expert", "Regulatory Compliance Specialist", "Board Advisory Professional"]',
  '[{"name": "Corporate Governance", "level": 94}, {"name": "Regulatory Compliance", "level": 96}, {"name": "Board Advisory", "level": 92}, {"name": "Risk Management", "level": 89}]',
  '[{"id": 1, "client": "Fortune 500 Company", "feedback": "Outstanding corporate governance expertise and strategic compliance guidance.", "rating": 5, "date": "2024-01-18", "projectType": "Corporate Governance"}, {"id": 2, "client": "Multinational Corp", "feedback": "Exceptional regulatory compliance framework development.", "rating": 5, "date": "2023-12-28", "projectType": "Regulatory Compliance"}]',
  '[{"title": "Corporate Governance Framework", "client": "Fortune 500 Company", "duration": "6 months", "status": "Completed"}, {"title": "Regulatory Compliance Audit", "client": "Multinational Corp", "duration": "4 months", "status": "In Progress"}]',
  '["Best Corporate Lawyer - Gurgaon 2023", "Excellence in Corporate Governance", "Top Regulatory Compliance Expert"]'
),
(
  'CA Rahul Verma',
  'Financial Controller & Tax Expert',
  'Tax Planning & Financial Strategy',
  'Specialized in tax planning, financial strategy, and corporate finance with expertise in optimizing tax structures and financial performance.',
  'CA Rahul Verma is a financial controller and tax expert with deep expertise in tax planning and financial strategy. He has helped numerous organizations optimize their tax structures and improve financial performance through strategic planning.',
  '13+ years',
  'finance',
  'premium',
  true,
  false,
  'Available',
  'rahul.verma@ureposh.com',
  '+91 98765 43217',
  'Hyderabad, India',
  'www.rahulverma.com',
  'linkedin.com/in/rahulverma',
  4.7,
  189,
  167,
  95,
  '5 hours',
  '₹5,500',
  '₹1,60,000',
  '₹30,000',
  'Calculator',
  'from-emerald-500 to-teal-600',
  'emerald',
  '["Tax Planning", "Financial Strategy", "Corporate Finance", "Tax Optimization", "Financial Analysis", "Strategic Planning"]',
  '["English", "Hindi", "Telugu"]',
  '[{"degree": "Chartered Accountant", "institution": "Institute of Chartered Accountants of India", "year": "2011"}, {"degree": "MBA Finance", "institution": "IIM Bangalore", "year": "2013"}]',
  '["Tax Planning Expert", "Financial Strategy Specialist", "Corporate Finance Professional"]',
  '[{"name": "Tax Planning", "level": 96}, {"name": "Financial Strategy", "level": 94}, {"name": "Corporate Finance", "level": 92}, {"name": "Tax Optimization", "level": 95}]',
  '[{"id": 1, "client": "Tech Giant", "feedback": "Exceptional tax planning strategies that saved us millions.", "rating": 5, "date": "2024-01-22", "projectType": "Tax Planning"}, {"id": 2, "client": "Manufacturing Corp", "feedback": "Outstanding financial strategy and optimization expertise.", "rating": 5, "date": "2023-12-30", "projectType": "Financial Strategy"}]',
  '[{"title": "Tax Optimization Strategy", "client": "Tech Giant", "duration": "5 months", "status": "Completed"}, {"title": "Financial Restructuring", "client": "Manufacturing Corp", "duration": "6 months", "status": "In Progress"}]',
  '["Best Tax Expert - Hyderabad 2023", "Excellence in Financial Strategy", "Top Corporate Finance Professional"]'
),
(
  'Dr. Anjali Patel',
  'Industrial Psychologist & Workplace Wellness Expert',
  'Employee Wellness & Organizational Health',
  'Specialized in industrial psychology, workplace wellness programs, and creating healthy organizational cultures with focus on mental health and well-being.',
  'Dr. Anjali Patel is an industrial psychologist and workplace wellness expert who specializes in creating healthy organizational cultures. Her expertise in mental health and well-being has transformed workplace environments across various industries.',
  '14+ years',
  'psychology',
  'premium',
  true,
  true,
  'Available',
  'anjali.patel@ureposh.com',
  '+91 98765 43218',
  'Ahmedabad, India',
  'www.anjalipatel.com',
  'linkedin.com/in/anjalipatel',
  4.9,
  234,
  198,
  98,
  '2 hours',
  '₹6,500',
  '₹1,80,000',
  '₹35,000',
  'Brain',
  'from-violet-500 to-purple-600',
  'violet',
  '["Industrial Psychology", "Workplace Wellness", "Mental Health", "Organizational Health", "Employee Engagement", "Wellness Programs"]',
  '["English", "Hindi", "Gujarati"]',
  '[{"degree": "Ph.D. Industrial Psychology", "institution": "Ahmedabad University", "year": "2010"}, {"degree": "M.A. Psychology", "institution": "Gujarat University", "year": "2007"}]',
  '["Licensed Industrial Psychologist", "Workplace Wellness Specialist", "Mental Health Expert"]',
  '[{"name": "Industrial Psychology", "level": 97}, {"name": "Workplace Wellness", "level": 95}, {"name": "Mental Health", "level": 96}, {"name": "Employee Engagement", "level": 93}]',
  '[{"id": 1, "client": "Healthcare Organization", "feedback": "Exceptional workplace wellness program that improved employee satisfaction by 40%.", "rating": 5, "date": "2024-01-25", "projectType": "Workplace Wellness"}, {"id": 2, "client": "IT Company", "feedback": "Outstanding mental health initiatives and organizational health improvements.", "rating": 5, "date": "2024-01-15", "projectType": "Mental Health"}]',
  '[{"title": "Workplace Wellness Program", "client": "Healthcare Organization", "duration": "8 months", "status": "Completed"}, {"title": "Mental Health Initiative", "client": "IT Company", "duration": "6 months", "status": "In Progress"}]',
  '["Best Industrial Psychologist - Gujarat 2023", "Excellence in Workplace Wellness", "Mental Health Champion Award"]'
);

-- Verify the data was inserted
SELECT 
  name, 
  title, 
  category, 
  rating, 
  verified, 
  featured,
  created_at
FROM people 
ORDER BY created_at DESC;
